---
  parserOptions:
    ecmaVersion: 7
    sourceType: module
    ecmaFeatures:
      impliedStrict: true
      jsx: true
      experimentalObjectRestSpread: true

  extends:
    - eslint:recommended
    - plugin:react/recommended

  plugins:
    - react

  env:
    browser: true
    es6: true

  #rules:

# vim: set ts=2 sw=2 et:
